spring:
  application:
    name: methods_of_jpa

  datasource:
    url: jdbc:mysql://localhost/sb_aug
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true